name: Deploy to Docker on Linux EC2

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3

   
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy and Run Docker
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
           
          sudo su

          mkdir Django-api

          cd Django-api

          git reset --hard origin/master 

          git pull origin master

          docker system prune -a

          -y

          docker build -t django-api .

          docker stop docker-api-container || true

          docker rm docker-api-container || true
          
          docker run -d \
            --name docker-api-container \
            -p 8000:8000 \
            django-api

          EOF
